### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by nsbatra** [appliedepi/epiRhandbook_vn#1]
A few changes to the first Welcome page (not urgent)
- [ ] "Editor-in-chief: Neale Batra" should change to "Editor: Neale Batra"
- [ ] The Citation should be changed to: "Batra, Neale, et al. The Epidemiologist R Handbook. 2021." (followed by the DOI as before)

@ntluong95

**Comment by ntluong95** [comment]
Thanks @nsbatra. I addressed those changes
