### ISSUE TITLE
Update my Linkedin profile in the handbook

### ISSUE THREAD

**Issue by huyenntk1996** [appliedepi/epiRhandbook_vn#2]
Dear Sir/Madam!
I'm one of the Vietnamese translators in the handbook. My LinkedIn has changed. Please change the link in this book:
https://www.linkedin.com/in/huyen-nguyen-thi-khanh-3920b51a6/
Thank you so much!
Best regards,
Huyen

**Comment by ntluong95** [comment]
Resolved!
